dist: focal
language: c++
before_install:
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 02FE5F12ADDE29B2
    - sudo echo "deb http://ppa.launchpad.net/tobydox/mingw-w64/ubuntu bionic main" >> /etc/apt/sources.list
    - sudo apt update
    - curl https://www.libsdl.org/release/SDL2-devel-2.0.12-mingw.tar.gz --output sdl2.tar.gz
    - tar xf sdl2.tar.gz
    - cd SDL2-2.0.12
    - sudo make install-package arch=x86_64-w64-mingw32 prefix=/usr/x86_64-w64-mingw32
    - sudo cp -r x86_64-w64-mingw32/include/SDL2 /usr/x86_64-w64-mingw32/include/
    - cd ..
    - curl https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-mingw.tar.gz --output sdlimg.tar.gz
    - tar xf sdlimg.tar.gz
    - cd SDL2_image-2.0.5
    - sudo make install-package arch=x86_64-w64-mingw32 prefix=/usr/x86_64-w64-mingw32
    - sudo cp -r x86_64-w64-mingw32/include/SDL2 /usr/x86_64-w64-mingw32/include/
    - cd ..
    - curl https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-mingw.tar.gz --output sdl2ttf.tar.gz
    - tar xf sdl2ttf.tar.gz
    - cd SDL2_ttf-2.0.15
    - sudo make install-package arch=x86_64-w64-mingw32 prefix=/usr/x86_64-w64-mingw32
    - sudo cp -r x86_64-w64-mingw32/include/SDL2 /usr/x86_64-w64-mingw32/include/
    - cd ..
    - sudo cp -r /usr/i686-w64-mingw32/include /usr/x86_64-w64-mingw32/include
    - ls /usr/include
    - sudo cp -r /usr/include/AL /usr/x86_64-w64-mingw32/include/
    - sudo cp -r /usr/include/vorbis /usr/x86_64-w64-mingw32/include/
    - sudo cp -r /usr/include/ogg /usr/x86_64-w64-mingw32/include/

addons:
  apt:
    packages:
      - build-essential
      - linux-libc-dev
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - gcc-7-multilib
      - gcc-aarch64-linux-gnu
      - gcc-powerpc-linux-gnu
      - libc6-arm64-cross
      - libc6-powerpc-cross
      - libc6-dev-arm64-cross
      - libc6-dev-powerpc-cross
      - g++-9
      - lcov
      - mingw-w64
      - gcc-mingw-w64-x86-64 
      - g++-mingw-w64-x86-64
      - libogg-dev
      - tree
      - libsndio-dev
      - libvorbis-dev
      - libopenal-dev
      - wine-stable
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev
      - libopenal-dev
      - libvorbis-dev

os:
    - linux

compiler:
    - g++

script:
    - travis/linux.sh
    - travis/windows.sh

